name: Continous Deployment Backend

on:
  workflow_dispatch:
  pull_request_target:
    types: [closed]
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven
      
      - name: Run tests and show output
        run: mvn -f backend/pom.xml clean verify -Dspring.profiles.active=test -X
      
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: backend/target/site/jacoco/

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -f ./docker/backend.dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

      - name: Trigger and Check Deploy Status
        run: |
          DEPLOY_ID=$(curl \
            --request POST \
            --url https://api.render.com/v1/services/${{secrets.BACKEND_RENDER_SERVICE_ID}}/deploys \
            --header 'authorization: Bearer ${{secrets.RENDER_API_KEY}}' \
            --header 'accept: application/json' \
            --header 'content-type: application/json' \
            --data '{ "clearCache": "do_not_clear" }' | jq -r '.id')

          previous_status=""
          while true; do
            sleep 10
            status=$(curl -s \
              --request GET \
              --url "https://api.render.com/v1/services/${{ secrets.BACKEND_RENDER_SERVICE_ID }}/deploys/$DEPLOY_ID" \
              --header "Authorization: Bearer ${{secrets.RENDER_API_KEY}}" \
              --header "Content-Type: application/json" | jq -r '.status')

            if [[ "$status" != "$previous_status" ]]; then
              echo "Deploy status: $status"
              previous_status="$status"
            fi

            if [[ "$status" == *"failed"* ]] || [[ "$status" == "canceled" ]] || [[ "$status" == "deactivated" ]]; then
              echo "Deploy status: $status"
              echo "Deployment failed"
              exit 1
            fi

            if [[ "$status" == "live" ]]; then
              echo "Deploy finished successfully"
              exit 0
            fi
          done
