name: Test Backend

on:
  workflow_dispatch:
  push:
    branches:
      - develop
  pull_request_target:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Construir e rodar testes
        run: |
          cd backend/src/main/java/com/mydeardiary
          mvn clean test 
          
